name: salt

dependencies:
  - pip=19.1.1
  - python=3.6.8
  - psutil
  - matplotlib
  - scikit-image

  - pip:
      - steppy==0.1.6
      - steppy-toolkit==0.1.5
      - neptune-client==0.3.0
      - neptune-contrib==0.9.2
      - imgaug==0.2.5
      - opencv_python==3.4.0.12
      - torch==0.3.1
      - torchvision==0.2.0
      - pretrainedmodels==0.7.0
      - pandas==0.24.2
      - numpy==1.16.4
      - cython==0.28.2
      - pycocotools==2.0.0

