project: shared/showroom

name: tgs_salt_identification_challenge
tags: [solution-10]

parameters:
  # Data Paths
  train_images_dir: data/raw/train
  test_images_dir: data/raw/test
  metadata_filepath: data/meta/metadata.csv
  depths_filepath: data/meta/depths.csv
  auxiliary_metadata_filepath: data/meta/auxiliary_metadata.csv
  stacking_data_dir: data/stacking_data

  # Execution
  overwrite: 0
  num_workers: 4
  num_threads: 4
  kaggle_message: 'solution-10'
  image_source: disk
  pin_memory: 1
  loader_mode: resize_and_pad
  target_format: 'png'
  pad_method: edge
  resize_target_size: 102
  pad_size: 13
  dev_mode_size: 100
  n_cv_splits: 6
  shuffle: 1

  # General parameters
  image_h: 128
  image_w: 128
  image_channels: 3

  # U-Net parameters
  network_output_channels: 2
  network_activation: 'sigmoid'
  architecture: UNetResNet # choose an option from models.ARCHITECTURES for example, EmptinessClassifier
  fine_tuning: 0

  # U-Net from scratch parameters
  nr_network_outputs: 1
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

  # Loss

  # Training schedule
  epochs_nr: 10000
  batch_size_train: 24
  batch_size_inference: 24
  lr: 0.0001
  momentum: 0.9
  patience: 20
  validation_metric_name: 'iout'
  minimize_validation_metric: 0

  # Exponential LR scheduler
  gamma: 0.95

  # Reduce LR on plateau
  reduce_factor: 0.1
  reduce_patience: 10
  min_lr: 1e-7


  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.0
  dropout_dense: 0.0

  # Postprocessing
  threshold_masks: 0.5
  tta_aggregation_method: mean
