#project: USERNAME/PROJECT_NAME

name: tgs_salt_identification_challenge
tags: [solution-5]

metric:
  channel: 'IOUT'
  goal: maximize

#Comment out if not in Cloud Environment
pip-requirements-file: requirements.txt

exclude:
- .git
- .idea
- .ipynb_checkpoints
- output
- imgs
- neptune.log
- offline_job.log
- notebooks

parameters:
  # Data Paths
  train_images_dir: /public/challenges/kaggle-salt-identification/train
  test_images_dir: /public/challenges/kaggle-salt-identification/test
  metadata_filepath: /output/metadata.csv # if you are loading from previous experiment change it to  /input/metadata.csv
  depths_filepath: /public/challenges/kaggle-salt-identification/depths.csv

  # Execution
  overwrite: 0
  num_workers: 4
  num_threads: 4
  kaggle_message: 'solution-5'
  image_source: disk
  pin_memory: 1
  loader_mode: resize_and_pad
  pad_method: reflect
  resize_target_size: 102
  pad_size: 13
  target_format: 'png'
  dev_mode_size: 100
  n_cv_splits: 6
  shuffle: 1

  # General parameters
  image_h: 128
  image_w: 128
  image_channels: 3

  # U-Net parameters
  unet_output_channels: 2
  unet_activation: 'sigmoid'
  encoder: ResNet152
  fine_tuning: 1

  # U-Net from scratch parameters
  nr_unet_outputs: 1
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

  # Loss
  dice_weight: 0.0
  bce_weight: 1.0

  # Training schedule
  epochs_nr: 10000
  batch_size_train: 24
  batch_size_inference: 64
  lr: 0.0001
  momentum: 0.9
  gamma: 0.95
  patience: 20
  validation_metric_name: 'iout'
  minimize_validation_metric: 0

  # Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.0
  dropout_dense: 0.0

  # Postprocessing
  threshold_masks: 0.5
  tta_aggregation_method: mean
